In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\dsawa\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\dsawa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dsawa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\dsawa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\dsawa\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### Reading the Dataset using pandas read_csv function

In [14]:
import pandas as pd

df= pd.read_csv("tweets_Dataset.csv")

df

,ID,UserName,Tweets,Date,Source
0,2549585622,Enhancv,ChatGPT has done it again! Check out the amazi...,2023-02-28 23:59:44,Zapier.com
1,1605221195258937347,AI_Dev_News,explores how Facebook and Snap are leveraging ...,2023-02-28 23:59:38,AI Dev News
2,1515792169050963968,Mazidul85504766,RT @gomezidao: Gomezi Network:\n- large open s...,2023-02-28 23:59:21,Twitter for Android
3,1236038375175569408,MurphysPodcast,RT @CultCouncilPod: Culture Council Podcast - ...,2023-02-28 23:59:15,Twitter for iPhone
4,1259884055635431424,conanyb6,RT @gomezidao: Gomezi Network:\n- large open s...,2023-02-28 23:59:12,Twitter Web App
...,...,...,...,...,...
416536,1002656214474342400,itsgreenbox,Love this set up üëåüèº The Alien by @cloudvapes i...,2018-08-26 18:29:01+00:00,Sprout Social
416537,45585604,DKCanada,Only four sleeps until #FanExpo in #Toronto! T...,2018-08-26 18:27:00+00:00,TweetDeck
416538,931959997784903681,Adriancryp,25 Machine Learning Startups To Watch in 2018\...,2018-08-26 18:26:37+00:00,Twitter for Android
416539,35411199,stockerblog,Here Come the #Humanoids \nhttps://t.co/vEj3Z0...,2018-08-26 18:26:18+00:00,Twitter Web Client
416540,1594685066,as_algogandi,What could #AI do in the #future... Would we b...,2018-08-26 18:19:54+00:00,Twitter for iPhone

In [15]:
# Attributes of Dataset before Pre-Processing

df.shape

(416541, 5)

In [16]:
df.size

2082705

In [17]:
# Get the memory usage of the DataFrame in bytes
memory_usage_bytes = df.memory_usage(deep=True).sum()

# Convert the memory usage to megabytes
memory_usage_MB = memory_usage_bytes / (1024 * 1024)

# Print the memory usage in MB
print(f"Memory usage: {memory_usage_MB:.2f} MB")

Memory usage: 248.31 MB

## Data Pre-Processing

In [18]:
# To Check the null values

# Count the number of NaN values in each row
nan_rows = df.isna().sum(axis=1)
print(nan_rows)

# Count the number of rows with at least one NaN value
num_nan_rows = nan_rows[nan_rows > 0].count()

# Print the result
print(f'The dataset has {num_nan_rows} rows with at least one NaN value.')

0         0
1         0
2         0
3         0
4         0
         ..
416536    0
416537    0
416538    0
416539    0
416540    0
Length: 416541, dtype: int64
The dataset has 27444 rows with at least one NaN value.

In [19]:
#Remove the NaN Value

df = df.dropna()

df

,ID,UserName,Tweets,Date,Source
0,2549585622,Enhancv,ChatGPT has done it again! Check out the amazi...,2023-02-28 23:59:44,Zapier.com
1,1605221195258937347,AI_Dev_News,explores how Facebook and Snap are leveraging ...,2023-02-28 23:59:38,AI Dev News
2,1515792169050963968,Mazidul85504766,RT @gomezidao: Gomezi Network:\n- large open s...,2023-02-28 23:59:21,Twitter for Android
3,1236038375175569408,MurphysPodcast,RT @CultCouncilPod: Culture Council Podcast - ...,2023-02-28 23:59:15,Twitter for iPhone
4,1259884055635431424,conanyb6,RT @gomezidao: Gomezi Network:\n- large open s...,2023-02-28 23:59:12,Twitter Web App
...,...,...,...,...,...
416536,1002656214474342400,itsgreenbox,Love this set up üëåüèº The Alien by @cloudvapes i...,2018-08-26 18:29:01+00:00,Sprout Social
416537,45585604,DKCanada,Only four sleeps until #FanExpo in #Toronto! T...,2018-08-26 18:27:00+00:00,TweetDeck
416538,931959997784903681,Adriancryp,25 Machine Learning Startups To Watch in 2018\...,2018-08-26 18:26:37+00:00,Twitter for Android
416539,35411199,stockerblog,Here Come the #Humanoids \nhttps://t.co/vEj3Z0...,2018-08-26 18:26:18+00:00,Twitter Web Client
416540,1594685066,as_algogandi,What could #AI do in the #future... Would we b...,2018-08-26 18:19:54+00:00,Twitter for iPhone

In [21]:
# To Check the duplicate Rows

duplicate_rows = df.duplicated()

# Print the number of duplicate rows
print(f'The dataset has {duplicate_rows.sum()} duplicate rows.')

# Print the duplicate rows
df[duplicate_rows]

The dataset has 51524 duplicate rows.

,ID,UserName,Tweets,Date,Source
396,121526589,ADaddyBlog,What Parents Need to Know About ChatGPT ü§ñ http...,2023-02-28 23:51:06,Twitter Web App
397,91608548,bamitav,"RT @bamitav: #Meta launches #LLaMA model, a re...",2023-02-28 18:15:31,Twitter for Android
398,91608548,bamitav,RT @bamitav: Zuckerbergs #Meta Joins AI #chatb...,2023-02-28 18:15:24,Twitter for Android
399,91608548,bamitav,RT @bamitav: #ElonMusk too is scared of ChatGP...,2023-02-28 18:14:39,Twitter for Android
400,291295049,SavvasKonst,@Google started to become unreliable after the...,2023-02-28 17:51:28,Twitter for Android
...,...,...,...,...,...
414531,1004429909215858688,MattyBv3,#Repost @mikequindazzi via \nhttps://t.co/eSNy...,2018-08-28 22:52:37+00:00,IFTTT
414542,276850731,therajnair,5 ways the #WorldEconomicForum says #AI is cha...,2018-08-28 22:10:04+00:00,Hootsuite Inc.
414547,491460384,MESAlliance,M&amp;E Journal: Maintain Your Creative Focus:...,2018-08-28 22:00:39+00:00,Blog2Social APP
414549,75212322,mandedaily,M&amp;E Journal: Maintain Your Creative Focus:...,2018-08-28 22:00:18+00:00,Blog2Social APP
414550,2895535734,JeffreyBuskey,Google bets on artificial intelligence &amp; m...,2018-08-28 22:00:14+00:00,Buffer

In [24]:
# To Remove duplicate rows

df= df.drop_duplicates()

df

,ID,UserName,Tweets,Date,Source
0,2549585622,Enhancv,ChatGPT has done it again! Check out the amazi...,2023-02-28 23:59:44,Zapier.com
1,1605221195258937347,AI_Dev_News,explores how Facebook and Snap are leveraging ...,2023-02-28 23:59:38,AI Dev News
2,1515792169050963968,Mazidul85504766,RT @gomezidao: Gomezi Network:\n- large open s...,2023-02-28 23:59:21,Twitter for Android
3,1236038375175569408,MurphysPodcast,RT @CultCouncilPod: Culture Council Podcast - ...,2023-02-28 23:59:15,Twitter for iPhone
4,1259884055635431424,conanyb6,RT @gomezidao: Gomezi Network:\n- large open s...,2023-02-28 23:59:12,Twitter Web App
...,...,...,...,...,...
416536,1002656214474342400,itsgreenbox,Love this set up üëåüèº The Alien by @cloudvapes i...,2018-08-26 18:29:01+00:00,Sprout Social
416537,45585604,DKCanada,Only four sleeps until #FanExpo in #Toronto! T...,2018-08-26 18:27:00+00:00,TweetDeck
416538,931959997784903681,Adriancryp,25 Machine Learning Startups To Watch in 2018\...,2018-08-26 18:26:37+00:00,Twitter for Android
416539,35411199,stockerblog,Here Come the #Humanoids \nhttps://t.co/vEj3Z0...,2018-08-26 18:26:18+00:00,Twitter Web Client
416540,1594685066,as_algogandi,What could #AI do in the #future... Would we b...,2018-08-26 18:19:54+00:00,Twitter for iPhone

In [25]:
#  Attributes of Dataset after Pre-Processing
df.shape

(337573, 5)

In [26]:
df.to_csv("tweets_cleaned.csv")